#ifndef AR_PATHMAPRESOLVER_DEBUGCODES_H
#define AR_PATHMAPRESOLVER_DEBUGCODES_H

#include <pxr/pxr.h>
#include <pxr/base/tf/debug.h>

PXR_NAMESPACE_OPEN_SCOPE

TF_DEBUG_CODES(
    AR_PATHMAPRESOLVER,
    AR_PATHMAPRESOLVER_CONTEXT
);

PXR_NAMESPACE_CLOSE_SCOPE

#endif // AR_PATHMAPRESOLVER_DEBUGCODES_H